before:
  hooks:
    - go mod download
builds:
  - id: bs-blacklister
    main: ./cmd/bs-blacklister/bs-blacklister.go
    binary: bs-blacklister
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
  - id: bs-configapi
    main: ./cmd/bs-configapi/bs-configapi.go
    binary: bs-configapi
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
  - id: bs-crawler
    main: ./cmd/bs-crawler/bs-crawler.go
    binary: bs-crawler
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
  - id: bs-indexer
    main: ./cmd/bs-indexer/bs-indexer.go
    binary: bs-indexer
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
  - id: bs-scheduler
    main: ./cmd/bs-scheduler/bs-scheduler.go
    binary: bs-scheduler
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "darkspot/bs-blacklister:latest"
      - "darkspot/bs-blacklister:{{ replace .Tag \"v\" \"\" }}"
      - "darkspot/bs-blacklister:{{ .Major }}"
    skip_push: false
    dockerfile: build/docker/Dockerfile.blacklister
  - goos: linux
    goarch: amd64
    image_templates:
      - "darkspot/bs-configapi:latest"
      - "darkspot/bs-configapi:{{ replace .Tag \"v\" \"\" }}"
      - "darkspot/bs-configapi:{{ .Major }}"
    skip_push: false
    dockerfile: build/docker/Dockerfile.configapi
  - goos: linux
    goarch: amd64
    image_templates:
      - "darkspot/bs-crawler:latest"
      - "darkspot/bs-crawler:{{ replace .Tag \"v\" \"\" }}"
      - "darkspot/bs-crawler:{{ .Major }}"
    skip_push: false
    dockerfile: build/docker/Dockerfile.crawler
  - goos: linux
    goarch: amd64
    image_templates:
      - "darkspot/bs-indexer:latest"
      - "darkspot/bs-indexer:{{ replace .Tag \"v\" \"\" }}"
      - "darkspot/bs-indexer:{{ .Major }}"
    skip_push: false
    dockerfile: build/docker/Dockerfile.indexer
  - goos: linux
    goarch: amd64
    image_templates:
      - "darkspot/bs-scheduler:latest"
      - "darkspot/bs-scheduler:{{ replace .Tag \"v\" \"\" }}"
      - "darkspot/bs-scheduler:{{ .Major }}"
    skip_push: false
    dockerfile: build/docker/Dockerfile.scheduler
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"
release:
  prerelease: true