version: '3'

services:
  nats:
    image: nats:2.1.6-alpine3.11
    logging:
      driver: none
  torproxy:
    image: dperson/torproxy:latest
    logging:
      driver: none
  elasticsearch:
    image: elasticsearch:7.5.1
    logging:
      driver: none
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: kibana:7.5.1
    logging:
      driver: none
    depends_on:
      - elasticsearch
    ports:
      - 15004:5601
  crawler:
    image: trandoshan.io/crawler:latest
    command: --log-level debug --nats-uri nats --tor-uri torproxy:9050
    restart: always
    depends_on:
      - nats
      - torproxy
  scheduler:
    image: trandoshan.io/scheduler:latest
    command: --log-level debug --nats-uri nats --api-uri http://api:8080
    restart: always
    depends_on:
      - nats
  persister:
    image: trandoshan.io/persister:latest
    command: --log-level debug --nats-uri nats --api-uri http://api:8080
    restart: always
    depends_on:
      - nats
      - api
  api:
    image: trandoshan.io/api:latest
    command: --log-level debug --nats-uri nats --elasticsearch-uri http://elasticsearch:9200
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - 15005:8080

volumes:
  esdata:
    driver: local
